CREATE TABLE [ref].[Protocol] (
    [ID]                      TINYINT       IDENTITY (1, 1) NOT NULL,
    [ProtocolName]            VARCHAR (200) NOT NULL,
    [Description]             VARCHAR (400) NULL,
    [DataStoreReferenceCode]  INT           NOT NULL,
    [URL]                     VARCHAR (200) NOT NULL,
    [BeginImplementationDate] DATETIME2 (0) NOT NULL,
    [EndImplementationDate]   DATETIME2 (0) NULL,
    [CreatedDate]             DATETIME2 (0) NOT NULL DEFAULT (getdate()),
    CONSTRAINT [PK_ProtocolConfiguration] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CK_ProtocolConfiguration_Description_DisallowZeroLength] CHECK (len([Description])>(0)),
    CONSTRAINT [CK_ProtocolConfiguration_ProtocolName_DisallowZeroLength] CHECK (len([ProtocolName])>(0)),
    CONSTRAINT [CK_ProtocolConfiguration_URL_DisallowZeroLength] CHECK (len([URL])>(0)),
    CONSTRAINT [UN_Protocol_ProtocolName] UNIQUE NONCLUSTERED ([ProtocolName] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to each version of the monitoring protocol', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Protocol Configuration ID autogenerated identifier', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Simple name for protocol configuration (should likely include version)', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'ProtocolName';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Brief description of protocol configuration', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'Description';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Data Store reference code that points to full description/content of protocol configuration', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'DataStoreReferenceCode';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'URL that points to full description/content of protocol configuration', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'URL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date that protocol configuration was first used in field', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'BeginImplementationDate';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date that protocol configuration was last used in field', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'EndImplementationDate';


GO



GO



GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date the record was created', @level0type = N'SCHEMA', @level0name = N'ref', @level1type = N'TABLE', @level1name = N'Protocol', @level2type = N'COLUMN', @level2name = N'CreatedDate';


GO


